#!/bin/bash

# Configuration paths
MODULE_NAME="picolink_mfd"
# Updated to match the build script's output location
MODULE_SRC="$(pwd)/kernel/build/picolink_mfd.ko"
INSTALL_MOD_PATH="/lib/modules/$(uname -r)/extra"
PERSIST_CONFIG_SCRIPT="/usr/local/bin/picolink_setup.sh"
SERVICE_NAME="picolink-config.service"
UDEV_RULE_FILE="/etc/udev/rules.d/99-picolink.rules"
DEV_NODE="/dev/picolink"

# Root privilege check
if [ "$EUID" -ne 0 ]; then
    echo "Error: Please run as root (use sudo)."
    exit 1
fi

# 0. Service Management (Uninstall/Reinstall Check)
if [ -f "$UDEV_RULE_FILE" ] || [ -f "/etc/systemd/system/$SERVICE_NAME" ]; then
    echo -e "\n--- Existing Installation Detected ---"
    read -p "Service already exists. [u]ninstall or [r]einstall/overwrite? (u/r/skip): " s_choice
    if [[ "$s_choice" == "u" ]]; then
        echo "[*] Removing service and module..."
        systemctl stop "$SERVICE_NAME" 2>/dev/null
        systemctl disable "$SERVICE_NAME" 2>/dev/null
        rm -f "/etc/systemd/system/$SERVICE_NAME"
        rm -f "$UDEV_RULE_FILE"
        rm -f "$PERSIST_CONFIG_SCRIPT"
        rmmod "$MODULE_NAME" 2>/dev/null
        rm -f "$INSTALL_MOD_PATH/$MODULE_NAME.ko"
        depmod -a
        systemctl daemon-reload
        echo "[+] Uninstalled successfully."
        exit 0
    elif [[ "$s_choice" == "skip" ]]; then
        echo "[*] Proceeding without changes to service."
    fi
fi

echo "--- Initializing PicoLink MFD Module ---"

# 1. Reload the kernel module
if lsmod | grep -q "$MODULE_NAME"; then
    echo "[*] Removing existing module $MODULE_NAME..."
    rmmod "$MODULE_NAME"
fi

if [ -f "$MODULE_SRC" ]; then
    echo "[*] Inserting module from $MODULE_SRC..."
    insmod "$MODULE_SRC"
    sleep 1 
elif [ -f "$INSTALL_MOD_PATH/$MODULE_NAME.ko" ]; then
    echo "[*] Using installed module..."
    modprobe "$MODULE_NAME" 2>/dev/null || insmod "$INSTALL_MOD_PATH/$MODULE_NAME.ko"
else
    echo "Error: Module not found. Please run the build script first."
    exit 1
fi

if [ ! -e "$DEV_NODE" ]; then
    echo "Error: Device node $DEV_NODE was not created."
    exit 1
fi

# Parsing variables
SCL=""
SDA=""
RX=""
TX=""
declare -A LEDS

# 2. Process command line arguments (if any)
if [ $# -gt 0 ]; then
    for arg in "$@"; do
        case $arg in
            scl=*) SCL="${arg#*=}" ;;
            sda=*) SDA="${arg#*=}" ;;
            rx=*)  RX="${arg#*=}" ;;
            tx=*)  TX="${arg#*=}" ;;
            led*=*) 
                PIN=$(echo "${arg%=*}" | grep -oE '[0-9]+')
                TRIGGER="${arg#*=}"
                LEDS[$PIN]=$TRIGGER
                ;;
        esac
    done
else
    # 3. Interactive Mode
    echo "--- Interactive Configuration (Enter 0 to skip) ---"
    read -p "I2C SCL Pin: " SCL
    read -p "I2C SDA Pin: " SDA
    read -p "UART RX Pin: " RX
    read -p "UART TX Pin: " TX

    FIRST_LED=true
    while true; do
        read -p "Add LED on pin (or 0 to finish): " LPIN
        if [[ "$LPIN" == "0" || -z "$LPIN" ]]; then break; fi
        if [ "$FIRST_LED" = true ]; then
            echo -e "\n[*] Available system triggers:"
            [ -d /sys/class/leds ] && cat /sys/class/leds/$(ls /sys/class/leds | head -n 1)/trigger
            echo -e "\n"
            FIRST_LED=false
        fi
        read -p "Trigger for LED $LPIN (e.g., none, heartbeat, disk-activity): " LTRIG
        LEDS[$LPIN]=${LTRIG:-none}
    done
fi

# 4-6. Apply Settings (Functionized for reuse in persistence)
apply_config() {
    # I2C
    if [[ "$SCL" != "0" && -n "$SCL" ]]; then
        echo "i2c $SCL $SDA" > "$DEV_NODE"
        sleep 0.2
    fi
    # UART
    if [[ "$RX" != "0" && -n "$RX" ]]; then
        echo "uart $RX $TX" > "$DEV_NODE"
        sleep 0.2
    fi
    # LEDs
    for PIN in "${!LEDS[@]}"; do
        echo "led $PIN" > "$DEV_NODE"
        # Wait loop for sysfs
        for i in {1..10}; do
            [ -d "/sys/class/leds/picolink_led_$PIN" ] && break
            sleep 0.1
        done
        [ "${LEDS[$PIN]}" != "none" ] && echo "${LEDS[$PIN]}" > "/sys/class/leds/picolink_led_$PIN/trigger" 2>/dev/null
    done
}

apply_config

# 7. Persistence Setup
echo -e "\n--- Persistence Setup ---"
read -p "Do you want to install this configuration as a permanent service? (y/n): " p_choice
if [[ "$p_choice" == "y" ]]; then
    # a. Install module
    mkdir -p "$INSTALL_MOD_PATH"
    cp "$MODULE_SRC" "$INSTALL_MOD_PATH/"
    depmod -a

    # b. Create standalone setup script
    echo "#!/bin/bash" > "$PERSIST_CONFIG_SCRIPT"
    echo "# Auto-generated by PicoLink Setup Script" >> "$PERSIST_CONFIG_SCRIPT"
    echo "modprobe $MODULE_NAME" >> "$PERSIST_CONFIG_SCRIPT"
    echo "sleep 1" >> "$PERSIST_CONFIG_SCRIPT"
    [[ "$SCL" != "0" && -n "$SCL" ]] && echo "echo \"i2c $SCL $SDA\" > $DEV_NODE" >> "$PERSIST_CONFIG_SCRIPT"
    [[ "$RX" != "0" && -n "$RX" ]] && echo "echo \"uart $RX $TX\" > $DEV_NODE" >> "$PERSIST_CONFIG_SCRIPT"
    for PIN in "${!LEDS[@]}"; do
        echo "echo \"led $PIN\" > $DEV_NODE" >> "$PERSIST_CONFIG_SCRIPT"
        echo "sleep 0.5" >> "$PERSIST_CONFIG_SCRIPT"
        [[ "${LEDS[$PIN]}" != "none" ]] && echo "echo \"${LEDS[$PIN]}\" > /sys/class/leds/picolink_led_$PIN/trigger" >> "$PERSIST_CONFIG_SCRIPT"
    done
    chmod +x "$PERSIST_CONFIG_SCRIPT"

    # c. Create Systemd Service
    cat <<EOF > "/etc/systemd/system/$SERVICE_NAME"
[Unit]
Description=PicoLink MFD Pin Configuration
After=multi-user.target

[Service]
Type=oneshot
ExecStart=$PERSIST_CONFIG_SCRIPT
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

    # d. Create Udev Rule (triggers on specific VID:PID)
    echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1d50\", ATTR{idProduct}==\"6150\", TAG+=\"systemd\", ENV{SYSTEMD_WANTS}=\"$SERVICE_NAME\"" > "$UDEV_RULE_FILE"
    
    systemctl daemon-reload
    udevadm control --reload-rules
    systemctl enable picolink-config.service
    systemctl start picolink-config.service
    echo "[+] Persistence installed! The PicoLink will be configured automatically when plugged in."
    echo "If you need to change the configuration, just run this script again."
fi

# 8. Final Status
echo -e "\n--- PicoLink System Status ---"
i2cdetect -l | grep "Pico" || echo "I2C: Not activated"
for PIN in "${!LEDS[@]}"; do
    T=$(cat "/sys/class/leds/picolink_led_$PIN/trigger" 2>/dev/null | grep -o '\[.*\]')
    echo "LED $PIN: Active Trigger -> $T"
done
echo "--- Configuration Complete ---"